version: '3.7'

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
  web:
    image: nginx
    ports:
      - 8081:80
    volumes:
      - ./html:/usr/share/nginx/html
  netshoot:
    image: nicolaka/netshoot
    ports:
      - 8088:8088
    command: -s -p 8088
  connecttocloudnative:
    image: curlimages/curl
    command: -v http://172.17.0.1:8082
