---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inlets-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inlets-server
  template:
    metadata:
      labels:
        app: inlets-server
    spec:
      volumes:
      - name: tmp-cert
        emptyDir: {}
      containers:
      - name: inlets-server
        imagePullPolicy: IfNotPresent
        # L7
        # image: inlets/inlets:2.6.3
        # command: ["inlets"]
        # args:
        # - "server"
        # - "--token=abc"
        # - "--port=8081"
        # - "--control-port=8000"
        #ports:
        #- containerPort: 8000
        #- containerPort: 5432
        # L4
        volumeMounts:
        - mountPath: /tmp
          name: tmp-cert
        image: inlets/inlets-pro:0.6.0
        command: ["inlets-pro"]
        args:
        - "server"
        - "--auto-tls=false"
        - "--listen=:8000"
        - "--remote-tcp=172.17.0.1"
        - "--common-name=server"
        - "--token=abc"

---
apiVersion: v1
kind: Service
metadata:
  name: inlets-control
  labels:
    app: inlets-server
spec:
  type: NodePort
  ports:
    - name: inlets-control
      port: 8000
      protocol: TCP
      targetPort: 8000
      nodePort: 30080
  selector:
    app: inlets-server
---
apiVersion: v1
kind: Service
metadata:
  name: classic-service
  labels:
    app: inlets-server
spec:
  type: NodePort
  ports:
    - name: inlets-data
      port: 8088
      protocol: TCP
      targetPort: 8088
      nodePort: 30084
  selector:
    app: inlets-server
