---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inlets-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inlets-client
  template:
    metadata:
      labels:
        app: inlets-client
    spec:
      containers:
      - name: inlets-client
        imagePullPolicy: IfNotPresent
        # L7
        # image: inlets/inlets:2.6.3
        # command: ["inlets"]
        # args:
        # - "client"
        # - "--remote=172.17.0.1:30080"
        # - "--upstream=http://172.17.0.1:8081"
        # - "--token=abc"
        # L4
        image: inlets/inlets-pro:0.6.0
        command: ["inlets-pro"]
        args:
        - "client"
        - "--connect=ws://172.17.0.1:30080/connect"
        - "--tcp-ports=5432"
        - "--token=abc"
        - "--license=<LICENSE>"